import {
    DIDWithKeys,
    EthrDIDMethod,
    createCredential,
    createAndSignCredentialJWT,
    createPresentation,
    createAndSignPresentationJWT,
    JWTService,
    getSubjectFromVP,
    getCredentialsFromVP,
    getSupportedResolvers,
    verifyPresentationJWT,
    verifyDIDs,
    verifySchema,
    createCredentialFromSchema,
    verifyCredentialJWT,
    verifyRevocationStatus,
    SchemaManager,
    PROOF_OF_ADDRESS,
    PROOF_OF_NAME,
  } from "@jpmorganchase/onyx-ssi-sdk";
  